name: Release

on:
  workflow_dispatch:

jobs:
  commit:
    name: Check
    uses: vladdoster/.github/.github/workflows/commit.yml@master
  lint:
    name: Check
    uses: vladdoster/.github/.github/workflows/lint.yml@master
  release:
    name: Publish
    needs: [commit,lint]
    uses: vladdoster/.github/.github/workflows/release.yml@master
    secrets:
       github-token: ${{ secrets.GITHUB_TOKEN }}
